### ISSUE TITLE
False negative in `collapsing-console-sections-plugin`

### ISSUE THREAD

**Issue by basil** [daniel-beck/csp-scanner#11]
https://github.com/jenkinsci/collapsing-console-sections-plugin/blob/5685b78d0defbe4783f82d4dcf68bc1bde63f327/src/main/java/org/jvnet/hudson/plugins/collapsingconsolesections/CollapsingSectionAnnotator.java#L107 was detected via manual testing but not via `csp-scanner`.

**Comment by daniel-beck** [comment]
Is this a duplicate of #1 or feedback for #10?

**Comment by basil** [comment]
Duplicate of #1. I thought it would be helpful to collect as many examples as possible here to aid in the development of future fixes. If this isn't helpful, I will stop leaving examples of existing issues.

**Comment by daniel-beck** [comment]
Reporting is fine, just didn't know how to interpret this.

**Comment by daniel-beck** [comment]
#11 is updated:

```
% java -jar target/csp-scanner.jar ~/collapsing-console-sections-plugin                                         
== Inline Event Handler (Java)
File: /Users/danielbeck/collapsing-console-sections-plugin/src/main/java/org/jvnet/hudson/plugins/collapsingconsolesections/CollapsingSectionAnnotator.java
----
onClick=\"doToggle(this)\">"
----
```
