### ISSUE TITLE
False negative in `junit`

### ISSUE THREAD

**Issue by basil** [daniel-beck/csp-scanner#2]
https://github.com/jenkinsci/junit-plugin/blob/06c2f7d93ac6a0e13e0e87ef1bda0652b33274dc/src/main/resources/hudson/tasks/test/AggregatedTestResultPublisher/config.jelly#L37 was detected by ATH but not `csp-scanner`.

**Comment by daniel-beck** [comment]
Good find, the rule is far too restrictive.
